# Generated by Django 3.0.4 on 2020-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=50)),
                ('FileName', models.CharField(max_length=50)),
                ('Explanation', models.CharField(max_length=50)),
                ('Status', models.SmallIntegerField(max_length=50)),
                ('isSent', models.BooleanField(max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameChannel', models.CharField(max_length=50, unique=True)),
                ('codeChannel', models.CharField(blank=True, max_length=50)),
                ('explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestDeadline', models.CharField(blank=True, max_length=50)),
                ('AverageSalary', models.IntegerField(blank=True, max_length=50)),
                ('Date', models.CharField(blank=True, max_length=50)),
                ('IssuerComment', models.CharField(blank=True, max_length=50)),
                ('HRComment', models.CharField(blank=True, max_length=50)),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('HRStatus', models.SmallIntegerField(blank=True, max_length=50)),
                ('ManagementStatus', models.SmallIntegerField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRequestChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRequestReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('vision', models.CharField(blank=True, max_length=50)),
                ('mBTI', models.CharField(blank=True, max_length=50)),
                ('explanation', models.CharField(blank=True, max_length=50)),
                ('revisionDate', models.CharField(blank=True, max_length=50)),
                ('yearOfExperience', models.IntegerField(blank=True, max_length=50)),
                ('sexuality', models.SmallIntegerField(blank=True, max_length=50)),
                ('fromAge', models.SmallIntegerField(blank=True, max_length=50)),
                ('toAge', models.SmallIntegerField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
                ('internship', models.BooleanField(blank=True, max_length=50)),
                ('educationalSubstitution', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileNumber', models.IntegerField(blank=True, max_length=50)),
                ('CardNumber', models.IntegerField(blank=True, max_length=50)),
                ('Code', models.IntegerField(blank=True, max_length=50)),
                ('FirstName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50)),
                ('FatherName', models.CharField(blank=True, max_length=50)),
                ('NationalCode', models.CharField(blank=True, max_length=50)),
                ('BirthCertificateNumber', models.CharField(blank=True, max_length=50)),
                ('IssueDate', models.CharField(blank=True, max_length=50)),
                ('BirthDate', models.CharField(blank=True, max_length=50)),
                ('DeathDate', models.CharField(blank=True, max_length=50)),
                ('MarriageDate', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('NFC', models.CharField(blank=True, max_length=50)),
                ('Password', models.CharField(blank=True, max_length=50)),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
                ('Sex', models.BooleanField(blank=True, max_length=50)),
                ('GetEmail', models.BooleanField(blank=True, max_length=50)),
                ('GetSMS', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonEmploymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('Date', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInterView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(blank=True, max_length=50)),
                ('Date', models.CharField(blank=True, max_length=50)),
                ('FromTime', models.DateTimeField(auto_now_add=True)),
                ('ToTime', models.DateTimeField(auto_now_add=True)),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(blank=True, max_length=50)),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeTypeCode', models.CharField(blank=True, max_length=50)),
                ('placeTypeName', models.CharField(blank=True, max_length=50)),
                ('finishedGoodProductAccountCode', models.CharField(blank=True, max_length=50)),
                ('rawMaterialAccountCode', models.CharField(blank=True, max_length=50)),
                ('explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('Code', models.CharField(blank=True, max_length=50)),
                ('Explanation', models.CharField(blank=True, max_length=50)),
                ('status', models.SmallIntegerField(blank=True, max_length=50)),
                ('isSent', models.BooleanField(blank=True, max_length=50)),
                ('isDeleted', models.BooleanField(blank=True, max_length=50)),
            ],
        ),
    ]
