# Generated by Django 3.0.4 on 2020-03-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='EmploymentRequest',
        ),
        migrations.DeleteModel(
            name='EmploymentRequestChannel',
        ),
        migrations.DeleteModel(
            name='EmploymentRequestReason',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonEmploymentRequest',
        ),
        migrations.DeleteModel(
            name='PersonInterView',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='PlaceType',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
